**Replace with your name and a brief description of the notebook.**

https://raw.githubusercontent.com/megan-owen/MAT328-Techniques_in_Data_Science/main/data/diabetes.csv# Homework 17

This homework uses the Pima Indian Diabetes dataset from Labs 14 and 15.  We will use decision trees and random forests to try to predict whether or not a person has diabetes.

Data URL:  [https://raw.githubusercontent.com/megan-owen/MAT328-Techniques_in_Data_Science/main/data/diabetes.csv]( https://raw.githubusercontent.com/megan-owen/MAT328-Techniques_in_Data_Science/main/data/diabetes.csv)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import confusion_matrix

import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

### Question 1: Loading and preparing the data

a) Load the data in your notebook.

In [2]:
diabetes = pd.read_csv("https://raw.githubusercontent.com/megan-owen/MAT328-Techniques_in_Data_Science/main/data/diabetes.csv")

1b) Create a DataFrame called `x` that contains all columns except `Outcome` (the independent variables).

In [3]:
x = diabetes.drop(columns=["Outcome"])

1c) Create a Series called `y` that contains the `Outcome` column (the dependent variable).

In [4]:
y = diabetes["Outcome"]

1d) Split variables `x` and `y` into training (80%) and testing (20%) data.

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, train_size = 0.8)

### Question 2: K-Nearest Neighbors Classifier

2a) Fit a k-nearest neighbors classifer with k=5 to the training data.

In [8]:
knn5 = KNeighborsClassifier(n_neighbors = 5)
knn5.fit(x_train, y_train)

KNeighborsClassifier()

2b) Use your classifier from 2a to predict the outcome for the test data.

In [9]:
y_test_preds = knn5.predict(x_test)

2c) Compute the confusion matrix for your predictions.

In [11]:
cm = confusion_matrix(y_test,y_test_preds)
cm

array([[88, 11],
       [25, 30]])

2d) How many true positives and true negatives are there?

**2d answer:** There are 30 true positives and 88 true negatives.

2e) Compute the sensitivity and specificity of this classifier.

In [12]:
true_pos = cm[1,1]
false_pos = cm[1,0]
false_neg = cm[0,1]
true_neg = cm[0,0]

In [13]:
sensitivity = true_pos/(true_pos + false_neg)
specificity = true_neg/(true_neg + false_pos)

print(f"Sensitivity: {sensitivity}\nSpecificity: {specificity}")

Sensitivity: 0.7317073170731707
Specificity: 0.7787610619469026


2f) Does the model do a better job predicting that people have diabetes or don't have it?

**2f answer:** It is pretty bad at both, thought it is slightly worse at predicting that people have it. The false negative error rate is higher than the false positive rate, but only by about `0.04`.

### Question 3: Testing a different parameter

a) Fit a second k-nearest neighbor classifier to the training data with a different k.

In [14]:
knn10 = KNeighborsClassifier(n_neighbors = 10)
knn10.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

3b) Use your classifier from 3a to predict the outcome for the test data.

In [15]:
y_test_preds = knn10.predict(x_test)

3c) Compute the confusion matrix, sensitivity, and specificity for your predictions from 3b.

In [16]:
cm = confusion_matrix(y_test,y_test_preds)
print(cm)
true_pos = cm[1,1]
false_pos = cm[1,0]
false_neg = cm[0,1]
true_neg = cm[0,0]
sensitivity = true_pos/(true_pos + false_neg)
specificity = true_neg/(true_neg + false_pos)
print(f"Sensitivity: {sensitivity}\nSpecificity: {specificity}")

[[90  9]
 [27 28]]
Sensitivity: 0.7567567567567568
Specificity: 0.7692307692307693


3d) Is this model better or worse than the model with k = 5?

**3d answer:** This model is worse than the model with k = 5 because both error rates are higher.

### Question 4: Testing a third parameter

a) Fit a third k-nearest neighbor classifier to the training data with a different k than 5 or the one used in Question 3.
, and use it to make predictions for the testing data. Compute the confusion matrix, sensitivity, and specificity. Is this model better or worse than the previous two k-nearest neighbor classifiers?

In [36]:
knn2 = KNeighborsClassifier(n_neighbors = 2)
knn2.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=2)

4b) Use your classifier from 4a to predict the outcome for the test data.

In [37]:
y_test_preds = knn2.predict(x_test)

4c) Compute the confusion matrix, sensitivity, and specificity for your predictions from 4b.

In [38]:
cm = confusion_matrix(y_test,y_test_preds)
print(cm)
true_pos = cm[1,1]
false_pos = cm[1,0]
false_neg = cm[0,1]
true_neg = cm[0,0]
sensitivity = true_pos/(true_pos + false_neg)
specificity = true_neg/(true_neg + false_pos)
print(f"Sensitivity: {sensitivity}\nSpecificity: {specificity}")

[[93  6]
 [33 22]]
Sensitivity: 0.7857142857142857
Specificity: 0.7380952380952381


4d) Is this model better or worse than the previous two k-nearest neighbor classifiers?

**4d answer:** This model has a better false negative error rate than both of the previous models, however, it's false positive error rate is the highest.

### Question 5: Comparison with other classifiers

Compare your best k-nearest neighbor classifier with the best classifier from Homework 16, Question 5d.  Which model would you use to predict diabetes in someone?  Why?  (If you did not complete that question in Homework 16, use the Homework 16 solutions.)

**Question 5 answer:** Between the two, the kmeans classifier where k = 2 is better. The sensitivity of the one in HW 16 Q5d was about 0.86, and its specificity was arounf 0.75 -- both of which were higher than this kmeans model.