**Replace with your name and a brief description of the notebook.**

# Homework 16

This homework uses the Pima Indian Diabetes dataset from Labs 14 and 15.  We will use decision trees and random forests to try to predict whether or not a person has diabetes.

Data URL:  [https://raw.githubusercontent.com/megan-owen/MAT328-Techniques_in_Data_Science/main/data/diabetes.csv]( https://raw.githubusercontent.com/megan-owen/MAT328-Techniques_in_Data_Science/main/data/diabetes.csv)

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import export_graphviz

from sklearn.metrics import confusion_matrix

import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

### Question 1: Loading and preparing the data

a) Load the data into your notebook.

In [3]:
diabetes = pd.read_csv("https://raw.githubusercontent.com/megan-owen/MAT328-Techniques_in_Data_Science/main/data/diabetes.csv")

1b) Split the data into a DataFrame called `x` that contains all columns except `Outcome` (the independent variables), and a Series called `y` that contains the `Outcome` column (the dependent variable)

In [4]:
x = diabetes.drop(columns=["Outcome"])
y = diabetes["Outcome"]

1c) Split your `x` and `y` variables from 1b into training (80%) and testing (20%) data

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

### Question 2: Decision tree with max depth 5

2a) Fit a decision tree with max depth 5 to the training data.

In [6]:
dt_model = DecisionTreeClassifier(max_depth = 5)
dt_model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5)

2b) Use your decision tree from 2a to predict `Outcome` for your testing data.

In [7]:
dt_y_pred_test = dt_model.predict(x_test)

2c) Compute the confusion matrix for your predictions.  How does it compare to the confusion matrix from Lab 15, Section 4?

In [8]:
conf_mat = confusion_matrix(y_test, dt_y_pred_test)
conf_mat

array([[85,  6],
       [27, 36]])

2d) How does this confusion matrix compare to the confusion matrix from Lab 15, Section 4?

**2d answer:** They both have a sizeable type II error rate, but all in all this model performed better as it's share of errors was less (~30%).

2e) Compute the sensitivity and specificity of your decision tree model.

In [9]:
true_pos = conf_mat[0][0]
false_pos = conf_mat[1][0]
false_neg = conf_mat[0][1]
true_neg = conf_mat[1][1]

In [10]:
sensitivity = true_pos/(true_pos + false_neg)
specificity = true_neg/(true_neg + false_pos)
print(f"Sensitivity: {sensitivity}\nSpecificity: {specificity}")

Sensitivity: 0.9340659340659341
Specificity: 0.5714285714285714


2f) Based on 2e, does this model do a better job predicting that people have diabetes or don't have it?

**2f answer:** According to these scores, it is not good at predicting whether or not people have diabetes. Its sensitivity indicates a high type II error rate, and its specificity indicates a moderate type I error rate.

### Question 3: Testing other parameters for the decision tree

a) Fit a decision tree with a different max depths on the training data, and use it to make predictions for the testing data.  Compute the confusion matrix.

In [11]:
dt2_model = DecisionTreeClassifier(max_depth = 10)
dt2_model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10)

In [12]:
dt_y_pred_test2 = dt2_model.predict(x_test)

In [13]:
conf_mat2 = confusion_matrix(y_test, dt_y_pred_test2)
conf_mat2

array([[75, 16],
       [22, 41]])

3b) Fit a decision tree with a different max depth than in question 2 or 3a on the training data, and use it to make predictions for the testing data.  Compute the confusion matrix.

In [14]:
dt3_model = DecisionTreeClassifier(max_depth = 2)
dt3_model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=2)

In [15]:
dt_y_pred_test3 = dt3_model.predict(x_test)

In [16]:
conf_mat3 = confusion_matrix(y_test, dt_y_pred_test3)
conf_mat3

array([[88,  3],
       [36, 27]])

3c) Of the three decision tree depths you have tested (Questions 2, 3a, 3b), which would you recommend for predicting diabetes?  Why?

**3c answer:** Based solely off of the confusion matrices, I would choose the first one with a depth of 5. This is because between all three it had the highest number of correct predictions.

### Question 4: Random forest

a) Fit a random forest with 500 estimators (random decision trees) of max depth 10 to the training data.

In [17]:
rf = RandomForestClassifier(n_estimators = 500, max_depth = 10)
rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=500)

4b) Use the random forest trained in 4a to predict the `Outcome` variable for the test data.

In [18]:
y_test_preds_rf = rf.predict(x_test)

4c) Compute the confusion matrix for your predictions.

In [19]:
conf_mat1 = confusion_matrix(y_test,y_test_preds_rf)
conf_mat1

array([[84,  7],
       [21, 42]])

4d) How does it compare to the confusion matrix from Lab 15, Section 4, and the best confusion matrix from Question 3c?

**4d answer:** It has a better TP and TN rate, which is good. But it still has a noticeable type I error rate.

4e) Compute the sensitivity and specificity of your random forest model.

In [20]:
true_pos1 = conf_mat1[0][0]
false_pos1 = conf_mat1[1][0]
false_neg1 = conf_mat1[0][1]
true_neg1 = conf_mat1[1][1]

In [21]:
sensitivity1 = true_pos1/(true_pos1 + false_neg1)
specificity1 = true_neg1/(true_neg1 + false_pos1)
print(f"Sensitivity: {sensitivity1}\nSpecificity: {specificity1}")

Sensitivity: 0.9230769230769231
Specificity: 0.6666666666666666


4f) Does the model do a better job predicting that people have diabetes or don't have it?

**4f answer:** It's sensitivity is slightly lower than that of the decision tree's, but its specificity is higher by ~0.2. Overall, it is not better than the decision tree at predicting whether someone has diabetes or not.

### Question 5: Testing other parameters for the random forest model

a) Fit another random forest with different parameters (number of estimators and max depth) on the training data, and use it to predict the variable `Outcome` for the testing data.  Compute the confusion matrix.

In [22]:
rf1 = RandomForestClassifier(n_estimators = 1000, max_depth = 15)
rf1.fit(x_train, y_train)

RandomForestClassifier(max_depth=15, n_estimators=1000)

In [23]:
y_test_preds_rf1 = rf1.predict(x_test)

In [24]:
conf_mat2 = confusion_matrix(y_test,y_test_preds_rf1)
conf_mat2

array([[81, 10],
       [22, 41]])

5b) Fit a third random forest with different parameters (number of estimators and max depth) on the training data, and use it to predict the variable `Outcome` for the testing data.  Compute the confusion matrix.

In [25]:
rf2 = RandomForestClassifier(n_estimators = 300, max_depth = 5)
rf2.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, n_estimators=300)

In [26]:
y_test_preds_rf2 = rf2.predict(x_test)

In [27]:
conf_mat3 = confusion_matrix(y_test,y_test_preds_rf2)
conf_mat3

array([[85,  6],
       [26, 37]])

5c) Of the three random forests you tested (Question 4, 5a, 5b), which would you recommend for predicting diabetes?  Why?

**5c answer:**  I would reccomend the third one because it made the most correct predictions and had the least type II error rate.

5d) Of the logistic regression model from Lab 15, Section 4, the best decision tree from Question 3c, and the best random forest from Question 5c, which model would you use to predict diabetes?  Why?

**5d answer:** I would reccomend the last random forest model tested in this homework (referenced in 5C) because of its lower FN / FP error rates. Especially with diabetes, a lower type II error rate is very important.